Release/staging
amazingengine/technology-weblog pull request #16
Opened 2019-08-16 10:48 UTC by cacapon

GCEのインスタンスをほぼ無料で立ち上げてみました
の記事を作成しました。ご確認をお願い致します。

2019-09-21 18:20 UTC, Amazingengine-yoshitaka requested changes
@cacapon 修正を御願い致します。

2019-09-21 18:20 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +<参考にしたURL> +
@cacapon 自社内だけで、全てを賄いたいです。なので、全て必要要素は、記載して下さい。

2019-09-21 18:20 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +* ブートディスクの容量は30GBまで無料なので30GBにします～
OS イメージにも言及して下さい。
「弊社の用途は Docker なので Docker と何かと相性が良い Debian 系を選びます」とか。

2019-09-21 18:20 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +
@cacapon `エフェメラル` の説明をしてこちらの方が使いたい場合はこちらにしては的な事を書いて下さい。

2019-09-21 18:20 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +image::cacapon/002/04_run_image.png[]
この画像の URL の部分と bookmark は消して下さい。

2019-09-21 18:20 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +https://qiita.com/hnw/items/8a422ccbc63dfbd9e3b9
これも、書かずに、文章を巧みに弊社のもので文章を記載して下さい。

2019-09-21 18:20 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +
求人を記載して下さい。

2019-12-13 01:44 UTC, cacapon commented
@Amazingengine-yoshitaka お手すきの際に、修正した文書の確認をお願いいたします。

2019-12-14 12:53 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +もし↑のリンクが終わってしまっていても大丈夫です～ +
こちらは Indeed のものだったので link が切れる可能性があったんで、これは切れる事は無いので消して下さい。

2019-12-14 12:53 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +image::cacapon/002/04_run_image.png[]
@cacapon cacapon/002/04_run_image.png の画像 URL が http://passed.jp/ になっているし、まだ `ブックマーク` も問題です。

2019-12-14 12:55 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +その際は、お手数ですが下記メールアドレスにご連絡ください♪
「何か、御相談したい事があれば下記に直接、御送り頂いても構いませんよ」的な感じに変更を宜しく御願い致します。

2019-12-14 13:55 UTC, Amazingengine-yoshitaka requested changes
https://en-gage.net/amazingengine/ の所在地の住所と https://en-gage.net/amazingengine/work_603910/ の企画職の住所が違うので全ての住所を
`東京都千代田区外神田2丁目1-8 道伝ビル B2F` に統一して下さい。
御手数ですが、御願い致します。

2019-12-14 13:55 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +https://en-gage.net/amazingengine/work_599313/?via_recruit_page=1[en-gage エンジニア職の募集はこちら]
?via_recruit_page=1 消しても大丈夫なので、消して下さい。

2019-12-14 13:55 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +https://en-gage.net/amazingengine/work_603910/?via_recruit_page=1[en-gage 企画職の募集はこちら]
?via_recruit_page=1 消しても大丈夫なので、消して下さい。

2019-12-14 13:55 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +https://en-gage.net/amazingengine/work_599313/?via_recruit_page=1[en-gage エンジニア職の募集はこちら]
[en-gage エンジニア職の募集はこちら] の en-gage では無く `engage` か `エンゲージ` です。

2019-12-14 13:55 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +https://en-gage.net/amazingengine/work_603910/?via_recruit_page=1[en-gage 企画職の募集はこちら]
[en-gage 企画職の募集はこちら] の en-gage では無く `engage` か `エンゲージ` です。

2019-12-14 14:10 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +https://english.passed.jp/
「https://english.passed.jp/ は build-redis-with-redis-persistent-storage-at-kubernetes/[KubernetesでRedis永続ストレージをもったRedisを建てよう] は Kubernetes でしたけど、この度 Docker に変更を致しました。」的な感じに変更して下さい。

2019-12-14 14:15 UTC, Amazingengine-yoshitaka commented on app/posts/lanch_a_gce_almost_free.adoc
> +https://english.passed.jp/
「https://english.passed.jp/ は build-redis-with-redis-persistent-storage-at-kubernetes/[KubernetesでRedis永続ストレージをもったRedisを建てよう] では Kubernetes でしたけど、この度 Docker に変更を致しました。」的な感じに変更して下さい。

2020-01-07 07:03 UTC, cacapon commented on app/posts/lanch_a_gce_almost_free.adoc
> +その際は、お手数ですが下記メールアドレスにご連絡ください♪
あまり意識しておりませんでしたが、HP上ですと
アドレスの`@`を`<at>`にしておりましたが、こちらも変えた方がよろしいでしょうか？

2020-01-07 07:36 UTC, cacapon commented
https://github.com/amazingengine/technology-weblog/pull/16#pullrequestreview-332212882
上記リンクで指摘を受けておりました住所に関しては修正いたしました。

2020-01-11 11:55 UTC, Amazingengine-yoshitaka approved these changes
LGTM. です。

2020-01-11 12:00 UTC, merged